### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tanu06** [LANL-Bioinformatics/FaQCs#5]
Trying QC, getting this error. Installed the packages using cpan.
 Command : perl  FaQCs.pl -p s301/s301_R1.fastq -d out_directory -qc_only
Bareword found where operator expected at FaQCs.pl line 6, near ""en" class"
        (Missing operator before class?)
Bareword found where operator expected at FaQCs.pl line 26, near "<title>FaQCs"
        (Missing operator before FaQCs?)
Can't modify numeric lt (<) in scalar assignment at FaQCs.pl line 6, near ""en" class"
syntax error at FaQCs.pl line 6, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 37 at FaQCs.pl line 26.

**Comment by tanu06** [comment]
Does this perl script works on single PE data??

**Comment by chienchi** [comment]
If just input one file of the PE data, it should print below message.

ex: perl FaQCs.pl -p example/input/reads1.fastq -d test

---

 Please check paired data input are even file numbers

 perl FaQCs.pl [options] [-u unpaired.fastq] -p reads1.fastq reads2.fastq -d out_directory

 Option -h to see full usage
